name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow when changes are pushed to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch submodules if using a theme
          fetch-depth: 0

      # Step 2: Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Step 3: Build the Hugo site
      - name: Build Hugo site
        run: hugo --minify

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # Deploy to the gh-pages branch